# Generated by Django 2.2.11 on 2020-10-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_movie_actors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieusercomment',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
