# Generated by Django 2.2.11 on 2020-10-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_movieusercomment_is_spoiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieusercomment',
            name='movie',
            field=models.ForeignKey(on_delete=1, related_name='comments_movie', to='myapp.Movie'),
        ),
    ]
