# Generated by Django 2.2.11 on 2020-11-06 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201026_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('striped_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.User'),
        ),
        migrations.AddField(
            model_name='movieusercomment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.MovieUser'),
        ),
    ]
