# Generated by Django 2.2.11 on 2020-11-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20201107_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieusercomment',
            name='is_spoiler',
        ),
    ]
