# Generated by Django 2.2.11 on 2020-11-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_movie_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
