# Generated by Django 2.2.11 on 2020-11-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20201114_1514'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movieusercomment',
            index=models.Index(fields=['movie'], name='myapp_movie_movie_i_a04722_idx'),
        ),
    ]
