# Generated by Django 2.2.11 on 2020-10-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201025_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieusercomment',
            name='is_spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
