# Generated by Django 2.2.11 on 2020-11-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201106_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieusercomment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='movieuser',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='movieuser',
            name='striped_id',
        ),
    ]
