# Generated by Django 2.2.11 on 2020-11-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20201110_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
