# Generated by Django 2.2.11 on 2020-11-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20201117_1830'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movieusercomment',
            index=models.Index(fields=['score'], name='myapp_movie_score_dc2fc0_idx'),
        ),
    ]
