# Generated by Django 2.2.11 on 2020-11-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20201117_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieuser',
            name='score_avg',
            field=models.IntegerField(null=True),
        ),
    ]
